// HERE GET ALL PRODUCT TYPES
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

// HERE GET ALL BRAND TYPES
export const GET_BRAND = 'GET_BRAND';  
export const GET_SINGLE_BRAND = 'GET_SINGLE_BRAND';

//HERE GET ALL CATEGORY TYPES
export const GET_CATEGORY = 'GET_CATEGORY'; 
export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY';  

//HERE POST LOGIN
export const POST_LOGIN = 'POST_LOGIN';

//HERE LOGOUT
export const LOGOUT = "LOGOUT";

//HERE POST CART
export const POST_CART = "POST_CART";
export const GET_CART = "GET_CART";
export const DELETE_CART = "DELETE_CART";

//HERE POST MESSAGE
export const POST_MESSAGE = "POST_MESSAGE";